# This docker will spin up a container with a postgres database.

services:
  db:
    container_name: mcp_app_db
    image: "ghcr.io/seuros/postgis-with-extensions:17-2"
    environment:
      POSTGRES_USER: ubuntu
      POSTGRES_PASSWORD: ubuntu
      POSTGRES_DB: my_mcp_app_development
    ports: [ "5466:5432" ]
