default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch("DATABASE_URL") { "postgresql://localhost:5432" } %>

development:
  <<: *default
  database: my_mcp_app_development

test:
  <<: *default
  database: my_mcp_app_test

production:
  primary: &primary_production
    <<: *default
    database: my_mcp_app_production
  cache:
    <<: *primary_production
    database: my_mcp_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: my_mcp_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: my_mcp_app_production_cable
    migrations_paths: db/cable_migrate
